export const EXCHANGES_TYPES = {
    GET_EXCHANGES: "GET_EXCHANGES",
    GET_EXCHANGES_SUCCESSFUL: "GET_EXCHANGES_SUCCESSFUL",
    GET_EXCHANGES_FAILURE: "GET_EXCHANGES_FAILURE"
}

export const MARKETS_TYPES = {
    GET_MARKETS: "GET_MARKETS",
    GET_MARKETS_SUCCESSFUL: "GET_MARKET_SUCCESSFUL",
    GET_MARKETS_FAILURE: "GET_MARKETS_FAILURE"
}

export const COINS_TYPES = {
    GET_COINS: "GET_COINS",
    GET_COINS_SUCCESSFUL: "GET_COIN_SUCCESSFUL",
    GET_COINS_FAILURE: "GET_COINS_FAILURE"
}