export const EXCHANGES_TYPES = {
    GET_EXCHANGES: "GET_EXCHANGES",
    GET_EXCHANGES_SUCCESSFUL: "GET_EXCHANGES_SUCCESSFUL",
    GET_EXCHANGES_FAILURE: "GET_EXCHANGES_FAILURE"
}

export const MARKETS_TYPES = {
    GET_MARKETS: "",
    GET_MARKETS_SUCCESSFUL: "",
    GET_MARKETS_FAILURE: ""
}