export const selectOpt = [
    "Bitcoin",
    "Ethereum",
    "Tether USD",
    'HEX',
    "Binance Coin",
    "Solana",
    "USDC",
    "Cardano",
    "XRP",
    "Polkadot",
    "Terra",
    "Dogecoin",
    "Avalanche",
    "SHIBA INU",
    'Polygon',
    'Binance USD',
    'Chainlink',
    'Wrapped BTC',
    "Cosmos",
    'Uniswap',
    'Litecoin',
    'Dai',
    'Algorand',
    'Bitcoin Cash',
    'OKB',
    'Decentraland',
    'Stellar',
    'VeChain',
    'FTX',
    'Compound Ether',
    'TRON',
    'Axie',
    'NEAR Protocol',
    'The Sandbox',
    'Theta Token',
    'PancakeSwap',
    'Hedera HashGraph',
    'LEO',
    'Tezos',
    'Ethereum Classic',
    'Monero',
    'Compound Dai',
    'Elrond',
    'AMP',
    'Klaytn',
    'Helium',
    '1inch Token',
    'Aave',
    'IOTA',
    'EOS',
    'Wootrade',
    'Filecoin',
    'Flow',
    'Gala',
    'Olympus',
    'MobileCoin',
    'Lido DAO Token',
    'Celsius Network',
    'Kusama',
    'SafeMoon',
    'Arweave',
    'TerraUSD',
    'Ravencoin',
    'Maker',
    'Curve DAO Token',
    'Bitcoin SV',
    'Frax',
    'One',
    'The Graph',
    'Stacks',
    'Zcash',
    'eCash',
    'Enjin Coin',
    'Quant',
    'NEO',
    'Huobi BTC',
    'SUSHI',
    'BitTorrent',
    'WAX Economic Token',
    'Basic Attention Token',
    'Chiliz',
    'Dash',
    'Waves',
    'KuCoin Token',
    'Huobi Token',
    'Loopring',
    'Nexo',
    'Compound',
    'yearn.finance',
    'USDi0',
    'Holo',
    'Ultra',
    'Paxos Standard',
    'XinFin Network',
    'Synthetix Network',
    'TrueUSD',
    'GateToken',
    'Theta Fuel',
]